; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Rzeczywista specyfikacja Twojej płytki (8MB Flash, No PSRAM)
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs

; Serial Monitor & Upload
monitor_speed = 115200
upload_speed = 921600

; Build Flags (wyłączono PSRAM, bo Twoja płytka go nie ma)
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1  ; To sprawia, że Serial działa od razu po starcie

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    ZinggJM/GxEPD2 @ ^1.6.5
